language: php
php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - nightly

env:
    - PHP_BIN=php
    - PHP_BIN=php-cgi

before_script:
    # Prefer IPv4 and use Cloudflare DNS by default, otherwise build could fail with timeouts.
    # https://getcomposer.org/doc/articles/troubleshooting.md#operation-timed-out-ipv6-issues-
    - sudo sh -c "echo 'precedence ::ffff:0:0/96 100' >> /etc/gai.conf" && sudo printf "nameserver 1.0.0.1\nnameserver 1.1.0.0\n" /etc/resolvconf/resolv.conf.d/base && sudo resolvconf -u
    - phpenv config-rm xdebug.ini || return 0
    - travis_retry composer self-update

install:
    - travis_retry composer install --no-interaction --no-progress --prefer-dist

script:
    - ./vendor/bin/nunjuck -p $PHP_BIN -s -c ./tests/php.ini ./tests

after_failure:
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
    include:
        -   stage: Code Sniffer
            php: 7.3
            script:
                - composer cs


        -   stage: Static Analysis
            php: 7.3
            script:
                - composer phpstan


        -   stage: Code Coverage
            php: 7.3
            script:
                - composer coverage
            after_script:
                - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
                - php coveralls.phar --verbose --config tests/.coveralls.yml

    allow_failures:
        -   stage: Static Analysis
        -   stage: Code Coverage
        -   php: 7.4
        -   php: nightly

sudo: required

cache:
    directories:
        - "$HOME/.composer/cache"

notifications:
    email: false
